# Generated by Django 2.2.4 on 2020-06-03 16:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_auto_20200531_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Product')),
                ('reciever', models.ForeignKey(db_column='reciever_id', on_delete=django.db.models.deletion.CASCADE, related_name='reciever_id', to='user.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('is_seen', models.BooleanField(blank=True, default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('thread', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.ThreadList')),
            ],
        ),
    ]
