# Generated by Django 2.2.4 on 2020-08-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadlist',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Product'),
        ),
        migrations.AddField(
            model_name='threadlist',
            name='reciever',
            field=models.ForeignKey(db_column='reciever_id', on_delete=django.db.models.deletion.CASCADE, related_name='reciever_id', to='user.User'),
        ),
        migrations.AddField(
            model_name='threadlist',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='messages',
            name='thread',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.ThreadList'),
        ),
    ]
