# Generated by Django 2.2.4 on 2020-05-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200411_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.URLField(blank=True, default='https://elysator.com/wp-content/uploads/blank-profile-picture-973460_1280-e1523978675847.png'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.URLField(blank=True, default='https://elysator.com/wp-content/uploads/blank-profile-picture-973460_1280-e1523978675847.png'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(default=None, null=True, related_name='cc', to='user.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=None, null=True, related_name='likces', to='user.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.URLField(blank=True, default='https://elysator.com/wp-content/uploads/blank-profile-picture-973460_1280-e1523978675847.png'),
        ),
    ]
