# Generated by Django 2.2.4 on 2020-05-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200528_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_cash',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='ordered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderby', to='user.User'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
