# Generated by Django 2.2.4 on 2020-06-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200531_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='reason_for_selling',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.TextField(default=''),
        ),
    ]
