# Generated by Django 2.2.4 on 2020-02-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200209_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fire_token',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=600),
        ),
    ]
