# Generated by Django 2.2.4 on 2020-02-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200209_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.CharField(default='', max_length=500)),
                ('about_us_ar', models.CharField(default='', max_length=500)),
                ('address', models.CharField(default='', max_length=500)),
                ('address_ar', models.CharField(default='', max_length=500)),
                ('working_hour', models.CharField(default='', max_length=500)),
                ('working_hour_ar', models.CharField(default='', max_length=500)),
                ('description_ar', models.CharField(default='', max_length=500)),
                ('phone', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
