# Generated by Django 2.2.4 on 2020-02-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='description_ar',
            new_name='phone_ar',
        ),
    ]
