# Generated by Django 2.2.4 on 2020-04-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_category_comments_media_order_product_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='comments',
            field=models.ManyToManyField(default=None, related_name='cc', to='user.Comments'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='likces', to='user.User'),
        ),
    ]
